<!-- Modal -->
<div class="modal fade" id="addplants" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <form id="plantForm" class="row g-3" method="POST" action="code.php" enctype="multipart/form-data">
          <div class="col-md-6">
            <div class="pic">
              <img src="pics/default.png" id="profile-pic" alt="Plant Preview">
            </div>
            </div>

            <div class="col-md-12">
              <label for="photo">Plants Photo<span style="color: red;"> *</span></label>
              <input type="file" class="form-control" name="plant_photo" id="plant_photo" onchange="displayImagePreview()" required>
            </div>

          <div class="col-md-12">
            <label for="selectPlant">Name of Plant<span style="color: red;"> *</span></label>
            <select class="form-control" aria-label="Name of Plant" id="plant_name" name="plant_name">
              <option value="" selected disabled>Select Plant Name</option>
            </select>
          </div>
          <div class="col-md-6">
            <label for="pHLevel">Required pH Level<span style="color: red;"> *</span></label>
            <input type="text" name="ph_lvl_low" class="form-control" id="ph_lvl_low" placeholder="generated by the system" required readonly>
          </div>
          <div class="col-md-6 mt-4">
            <label for="pHLevel"></label>
            <input type="text" name="ph_lvl_high" class="form-control" id="ph_lvl_high" placeholder="generated by the system" required readonly>
          </div>
          <div class="col-md-6">
            <label for="selectBay">Bay<span style="color: red;"> *</span></label>
            <select class="form-control" name="bay" id="selectBay" required>
              <option selected disabled>Select a Bay</option>
              <?php foreach ($bayData as $key => $row) {
                echo '<option value="' . $row['bay'] . '">' . $row['bay'] . '</option>';
              } ?>
            </select>
          </div>
          <div class="col-md-6">
            <label for="selectPipe">NFT<span style="color: red;"> *</span></label>
            <select class="form-control" name="nft" id="selectPipe" required>
              <option selected disabled>Select an NFT</option>
              <?php foreach ($nftData as $key => $row) {
                echo '<option value="' . $row['nft'] . '">' . $row['nft'] . '</option>';
              } ?>
            </select>
          </div>
          <div class="col-md-12">
            <label for="datePlanted">Date Planted<span style="color: red;"> *</span></label>
            <div class="input-group date" data-target-input="nearest">
              <input type="date" class="form-control" id="date_planted" name="date_planted" placeholder="Date Planted" data-target="#datePlanted" required min="<?= date('Y-m-d'); ?>" />
            </div>
          </div>
          <div class="col-md-12">
            <label for="estimatedHarvestDate">Estimated Harvest Date</label>
            <div class="input-group" data-target-input="nearest">
              <input type="date" class="form-control" id="date_harvest" name="date_harvest" placeholder="generated by the system" data-target="#estimatedHarvestDate" required readonly />
            </div>
          </div>
      </div>
      <div class="modal-footer justify-content-between mt-3">
        <button type="button" class="btn btn-secondary" data-mdb-ripple-init data-dismiss="modal">
          <i class="fa fa-close"></i> Close
        </button>
        <button type="submit" class="btn btn-primary" data-mdb-ripple-init name="add-plant-btn">
          <i class="fa fa-save"></i> Save
        </button>
        </form>
      </div>
    </div>
  </div>
</div>