<!-- Modal -->
<div class="modal fade" id="addplants" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <form id="plantForm" class="row g-3" method="POST" action="code.php" enctype="multipart/form-data">
          <div class="col-md-12">
            <div class="pic">
              <img src="pics/default.png" id="profile-pic" alt="Plant Preview">
            </div>
          </div>

          <div class="col-md-12">
            <label for="photo" class="form-label">Plants Photo</label>
            <input type="file" class="form-control" name="plant_photo" id="plant_photo" onchange="displayImagePreview()" required>
          </div>

          <div class="col-md-12">
            <label for="selectPlant" class="form-label">Name of Plant</label>
            <select class="form-select" aria-label="Name of Plant" id="plant_name" name="plant_name">
              <option value="" selected disabled>Select Plant Name</option>
            </select>
          </div>

          <div class="col-md-6">
            <label for="pHLevel" class="form-label">Lowest pH Level</label>
            <input type="text" name="ph_lvl_low" class="form-control" id="ph_lvl_low" placeholder="generated by the system" required readonly>
          </div>

          <div class="col-md-6">
          <label for="pHLevel" class="form-label">Highest pH Level</label>
            <label for="pHLevel" class="form-label">&nbsp;</label>
            <input type="text" name="ph_lvl_high" class="form-control" id="ph_lvl_high" placeholder="generated by the system" required readonly>
          </div>

          <div class="col-md-6">
            <label for="selectBay" class="form-label">Bayy</label>
            <select class="form-select" name="bay" id="selectBay" required>
              <option selected disabled>--Select--</option>
              <?php foreach ($bayData as $key => $row) {
                echo '<option value="' . $row['bay'] . '">' . $row['bay'] . '</option>';
              } ?>
            </select>
          </div>

          <div class="col-md-6">
            <label for="selectPipe" class="form-label">NFT and Kratk</label>
            <select class="form-select" name="nft" id="selectPipe" required>
              <option selected disabled>--Select--</option>
              <?php foreach ($nftData as $key => $row) {
                echo '<option value="' . $row['nft'] . '">' . $row['nft'] . '</option>';
              } ?>
            </select>
          </div>

          <div class="col-md-12">
            <label for="datePlanted" class="form-label">Date Planted</label>
            <input type="date" class="form-control" id="date_planted" name="date_planted" placeholder="Date Planted" required min="<?= date('Y-m-d'); ?>" />
          </div>

          <div class="col-md-12">
            <label for="estimatedHarvestDate" class="form-label">Estimated Harvest Date</label>
            <input type="date" class="form-control" id="date_harvest" name="date_harvest" placeholder="generated by the system" required readonly />
          </div>

          <div class="modal-footer justify-content-between mt-3">
            <button type="button" class="btn btn-secondary" data-mdb-ripple-init data-dismiss="modal">
              <i class="fa fa-close"></i> Close
            </button>
            <button type="submit" class="btn btn-primary" data-mdb-ripple-init name="add-plant-btn">
              <i class="fa fa-save"></i> Save
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>



  <!-- Delete Modal -->
  <div class="modal fade" id="deleteplant">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
        <h4 class="modal-title">Delete....</h4>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form class="form-horizontal" method="POST" action="code.php">
            <input type="hidden" class="plantid" name="id">
            <div class="text-center">
              <p>Are you sure you want to delete this plant?</p>
              <h2 class="bold delete_plant" id="delete_plant_name" name="plant_name"></h2>
            </div>
        </div>
        <div class="modal-footer justify-content-between mt-3">

                  <button type="button" class="btn btn-secondary"  data-bs-dismiss="modal">
                      <i class="fa fa-close"></i> Close</button>

                  <button type="submit" class="btn btn-danger" name="delete-plants-btn">
                    <i class="fa fa-trash"></i> Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
